version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform...
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  build:
    commands:
      - terraform init
      - echo Running Terraform code analysis
      - terraform validate
artifacts:
  files:
    - '**/*'
